easy_admin:
  entities:
    Box:
      class: App\Entity\Box
    Carte:
      class: App\Entity\Carte
    User:
      class: App\Entity\User

    Partie:
      class: App\Entity\Partie
    Jouer:
      class: App\Entity\Jouers